from flask_wtf import FlaskForm
from wtforms import SubmitField, RadioField, TextField, TextAreaField
from flask import render_template, url_for, flash, redirect, request
from wtforms_components import TimeField, SelectField, DateField, StringField

class feedback_form(FlaskForm):
	analyst_name = StringField('Submitter Email:')
	analyst_email = StringField('Customer Email:')
	name = StringField('As')
	job_title = StringField('A')
	company = SelectField('At', choices=[('Select Company', 'Select Company'),('Adina Katz', 'Adina Katz'), ('Alejandro Aguilera', 'Alejandro Aguilera'), ('Anakarina Lance', 'Anakarina Lance'), ('Andrew Rose', 'Andrew Rose'), ('Bernard Kavanagh', 'Bernard Kavanagh'), ('Brecht Vermeire', 'Brecht Vermeire'), ('Chris Seymour', 'Chris Seymour'), ('David Chiaramonte', 'David Chiaramonte'), ('David Hughes', 'David Hughes'), ('Deepika Raghavan', 'Deepika Raghavan'), ('Desiree Sugnet', 'Desiree Sugnet'), ('Diego Campos', 'Diego Campos'), ('Emma Wang', 'Emma Wang'), ('Eugene Lee', 'Eugene Lee'), ('Felix Jacob', 'Felix Jacob'), ('Fernanda Melo', 'Fernanda Melo'), ('Flávia Godoi de Oliveira', 'Flávia Godoi de Oliveira'), ('Gavin Wims', 'Gavin Wims'), ('Henry Watt', 'Henry Watt'), ('Iqbal Sandhu', 'Iqbal Sandhu'), ('Izzy Miller', 'Izzy Miller'), ('James Nestler', 'James Nestler'), ('Jeffrey Martinez', 'Jeffrey Martinez'), ('Jeremy Eckman', 'Jeremy Eckman'), ('Jesus Cruz-Cervantes', 'Jesus Cruz-Cervantes'), ('Jiro Wiseman', 'Jiro Wiseman'), ('Jon Allen', 'Jon Allen'), ('Jonathan Hester', 'Jonathan Hester'), ('Jonathan Reinhard', 'Jonathan Reinhard'), ('Kenelly Almeida', 'Kenelly Almeida'), ('Kevin Dunn', 'Kevin Dunn'), ('Lauren Boltz', 'Lauren Boltz'), ('Leticia Esparza', 'Leticia Esparza'), ('Makoto Ichihara', 'Makoto Ichihara'), ('Mandy Chan', 'Mandy Chan'), ('Margaret Abercrombie', 'Margaret Abercrombie'), ('Melissa Bard', 'Melissa Bard'), ('Milli Koch', 'Milli Koch'), ('Molly Lippsett', 'Molly Lippsett'), ('Morgan Imel', 'Morgan Imel'), ('Nathaniel Thompson', 'Nathaniel Thompson'), ('Noah Kawasaki', 'Noah Kawasaki'), ('Olga Dernovska', 'Olga Dernovska'), ('Olivia Pratt', 'Olivia Pratt'), ('Paola Renteria ', 'Paola Renteria '), ('Patricia Chai', 'Patricia Chai'), ('Peggy Beard', 'Peggy Beard'), ('Philip Martinelli', 'Philip Martinelli'), ('Quinn Morrison', 'Quinn Morrison'), ('Reed Rawlings', 'Reed Rawlings'), ('Romain Ducarrouge', 'Romain Ducarrouge'), ('Ruth McElroy', 'Ruth McElroy'), ('Ryan Bouquet', 'Ryan Bouquet'), ('Ryan Dunlavy', 'Ryan Dunlavy'), ('Ryland Wolff Baker', 'Ryland Wolff Baker'), ('Sam Asher', 'Sam Asher'), ('Sara Leon', 'Sara Leon'), ('Sasha Vedernikovs', 'Sasha Vedernikovs'), ('Sidney Junior', 'Sidney Junior'), ('Srinija Godavarthi', 'Srinija Godavarthi'), ('TJ Banghart', 'TJ Banghart'), ('Takuya Suzuki', 'Takuya Suzuki'), ('Talal Naboulsi', 'Talal Naboulsi'), ('Vitor Leepkaln', 'Vitor Leepkaln'), ('Will Adams', 'Will Adams'), ('William Lane', 'William Lane'), ('Won Kyoung Park', 'Won Kyoung Park'), ('Xin Bao', 'Xin Bao')])
	feedback = TextAreaField('I want...')
	use_case = TextAreaField('So that...')
	addt_info = TextAreaField('Additional Information:')
	submit = SubmitField('Submit')